# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('cover', models.BinaryField(blank=True, null=True)),
                ('discogs_link', models.CharField(blank=True, max_length=255, null=True)),
                ('directory', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'release',
                'managed': False,
            },
        ),
    ]
