# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemezpolc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={},
        ),
    ]
