# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemezpolc', '0002_auto_20170823_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='cover',
        ),
        migrations.AddField(
            model_name='release',
            name='cover_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
