# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemezpolc', '0003_auto_20170823_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='cover_path',
            new_name='cover',
        ),
    ]
