# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lemezpolc', '0004_auto_20170824_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
