# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemezpolc', '0005_auto_20170827_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='format',
            new_name='release_format',
        ),
    ]
